"""Add comments and unique constraint

Revision ID: 21a7a25b9f8d
Revises: ecbd597deabc
Create Date: 2026-08-28 10:54:00.579122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21a7a25b9f8d'
down_revision: Union[str, None] = 'ecbd597deabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_question_status', 'user_id',
               existing_type=sa.INTEGER(),
               comment='ID пользователя, владельца статуса',
               existing_nullable=False)
    op.alter_column('user_question_status', 'question_id',
               existing_type=sa.INTEGER(),
               comment='ID вопроса, к которому относится статус',
               existing_nullable=False)
    op.alter_column('user_question_status', 'status',
               existing_type=postgresql.ENUM('passed', 'not_passed', 'repeat', 'in_progress', name='question_status'),
               comment='Статус: passed - сдан, not_passed - не сдан, repeat - на повторение, in_progress - в процессе',
               existing_nullable=False,
               existing_server_default=sa.text("'not_passed'::question_status"))
    op.alter_column('user_question_status', 'attempts',
               existing_type=sa.INTEGER(),
               comment='Количество попыток ответить на вопрос',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_question_status', 'correct',
               existing_type=sa.INTEGER(),
               comment='Количество правильных ответов на вопрос',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_question_status', 'last_attempt_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Время последней попытки ответить на вопрос',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_question_status', 'last_attempt_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Время последней попытки ответить на вопрос',
               existing_nullable=True)
    op.alter_column('user_question_status', 'correct',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Количество правильных ответов на вопрос',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_question_status', 'attempts',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Количество попыток ответить на вопрос',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_question_status', 'status',
               existing_type=postgresql.ENUM('passed', 'not_passed', 'repeat', 'in_progress', name='question_status'),
               comment=None,
               existing_comment='Статус: passed - сдан, not_passed - не сдан, repeat - на повторение, in_progress - в процессе',
               existing_nullable=False,
               existing_server_default=sa.text("'not_passed'::question_status"))
    op.alter_column('user_question_status', 'question_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID вопроса, к которому относится статус',
               existing_nullable=False)
    op.alter_column('user_question_status', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID пользователя, владельца статуса',
               existing_nullable=False)
    # ### end Alembic commands ###
