"""Added new column

Revision ID: 41b91247239e
Revises: 21a7a25b9f8d
Create Date: 2026-09-02 11:55:47.292611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b91247239e'
down_revision: Union[str, None] = '21a7a25b9f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('tag', sa.String(length=50), nullable=True, comment='Группировка по тегам (Python, Web, SQL, DevOps, etc.)'))
    op.add_column('questions', sa.Column('category', sa.String(length=50), nullable=True, comment='Подгруппа (DDL, DML, ООП, Структуры данных, Алгоритмы, etc.)'))
    op.add_column('questions', sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty_level'), nullable=True, comment='Уровень сложности: easy, medium, hard'))
    op.alter_column('questions', 'question',
               existing_type=sa.TEXT(),
               comment='Текст вопроса',
               existing_nullable=False)
    op.alter_column('questions', 'answer',
               existing_type=sa.TEXT(),
               comment='Ответ на вопрос',
               existing_nullable=False)
    op.create_index(op.f('ix_questions_category'), 'questions', ['category'], unique=False)
    op.create_index(op.f('ix_questions_tag'), 'questions', ['tag'], unique=False)
    op.create_index('ix_questions_tag_category', 'questions', ['tag', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_questions_tag_category', table_name='questions')
    op.drop_index(op.f('ix_questions_tag'), table_name='questions')
    op.drop_index(op.f('ix_questions_category'), table_name='questions')
    op.alter_column('questions', 'answer',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ответ на вопрос',
               existing_nullable=False)
    op.alter_column('questions', 'question',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Текст вопроса',
               existing_nullable=False)
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'category')
    op.drop_column('questions', 'tag')
    # ### end Alembic commands ###
